"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Montserrat } from 'next/font/google';
import Navbar from "../components/Layout/Navbar/Navbar";
import { ethers } from "ethers";
import Cookies from "js-cookie";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });
// const montserrat = Montserrat({
//   subsets: ['latin'],
//   weight: ['400', '500', '700'], // Opsi bobot font
//   display: 'swap',
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if (typeof window !== "undefined" && window.ethereum) {
      window.ethereum.on("accountsChanged", async () => {
        const accounts = await window.ethereum.request({
          method: "eth_requestAccounts",
        });
        Cookies.remove("address");
        Cookies.remove("username");
        Cookies.remove("img");
  
        window.location.pathname = "/";
      });
    }
  }, []);
 
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#FFFFFF]`}>{children}</body>
    </html>
  );
}
